### PR TITLE
Update domain to new one set up due to coverbancho.tk expiring

### PR DESCRIPTION
**Pull request by xSkyyy**

### CODE REVIEW

**Comment by BoxDevelopment** [comment]
Hey I don't know if you will see this but if you do please show off the method of making a domain work for local osu server

Just incase if this domain expires people can self host their own or others can also use theirs to allow others to play

**Comment by jeevanjohnson** [comment]
> Hey I don't know if you will see this but if you do please show off the method of making a domain work for local osu server
> 
> Just incase if this domain expires people can self host their own or others can also use theirs to allow others to play

Indeed, I will be providing a guide on how to set up the domain properly. I'll be doing that in V3 if you are still curious.

**Comment by BoxDevelopment** [comment]
> > Hey I don't know if you will see this but if you do please show off the method of making a domain work for local osu server
> > Just incase if this domain expires people can self host their own or others can also use theirs to allow others to play
> 
> Indeed, I will be providing a guide on how to set up the domain properly. I'll be doing that V3 if you are still curious.

That would be perfect if you could <3

**Review by R1kkuChan — COMMENTED** [review]
can u add redirect to assets.? (assets.catboy.click) pls?

**Pull request closed without merging**
